In [11]:
#we need numpy to manipulate the ECG data and matpolit to plot it
import numpy as np
import matplotlib.pyplot as plt

In [18]:
#load the data into a numpy array
data = np.loadtxt("c:\\2SIA Montpellier\\Python -R-Git\\Serie01\\Series01-python\\Series01-Python\\ECGu.txt")


In [19]:
# Look at the data (verify that the data is loaded correctly)
print (data)

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
